## Занятие 7. Линейные модели для классификации

https://scikit-learn.ru/1-2-linear-and-quadratic-discriminant-analysis/

https://scikit-learn.ru/3-3-metrics-and-scoring-quantifying-the-quality-of-predictions/

In [21]:
#!pip install pingouin

In [31]:
import os
import numpy as np
import pandas as pd
from pandas import read_csv
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.svm import SVC
import pingouin as pg

### Logistic Regression

In [2]:
os.chdir("C:/Users/HP/Documents/analysis/Marketing/data/")

In [3]:
filename = 'pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(filename, names=names)

In [4]:
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]

In [5]:
kfold = KFold(n_splits=10, random_state=7, shuffle=True)

In [6]:
# Logistic Regression Classification
model = LogisticRegression(solver='liblinear')
results = cross_val_score(model, X, Y, cv=kfold)
print(results.mean())
print(results.std())

0.7708646616541353
0.05090500786917546


In [7]:
model.fit(X,Y)

LogisticRegression(solver='liblinear')

In [8]:
print("Форма коэффициентов: ", model.coef_.shape)
print("Форма константы: ", model.intercept_.shape)

Форма коэффициентов:  (1, 8)
Форма константы:  (1,)


In [9]:
model.coef_

array([[ 1.16994476e-01,  2.83733435e-02, -1.68981359e-02,
         7.55145090e-04, -6.41407258e-04,  5.97201268e-02,
         6.76128123e-01,  7.23498971e-03]])

In [10]:
model.intercept_

array([-5.88679617])

In [11]:
x_new=np.array([[0,136,42,34,136,43,2,32],[0,137,40,35,168,43.1,2.288,33]])

In [12]:
model.predict(x_new)

array([1., 1.])

In [14]:
model.predict_proba(x_new)

array([[0.20547146, 0.79452854],
       [0.16759435, 0.83240565]])

Для каждого наблюдения приведены вероятности 0-го класса (1-й столбец) и 1-го класса (2-й столбец).

### Support Vector Machines

https://scikit-learn.org/stable/modules/svm.html#svm-kernels

In [38]:
model = SVC(kernel='linear')
results = cross_val_score(model, X, Y, cv=kfold)
print(results.mean())
print(results.std())

0.7708133971291866
0.03832392703883875


In [39]:
model.fit(X,Y)

SVC(kernel='linear')

In [40]:
print("Форма коэффициентов: ", model.coef_.shape)
print("Форма константы: ", model.intercept_.shape)

Форма коэффициентов:  (1, 8)
Форма константы:  (1,)


In [41]:
model.coef_

array([[ 9.14692398e-02,  3.00467168e-02, -1.09051239e-02,
        -4.81652166e-03, -4.21253324e-04,  7.33928948e-02,
         7.15054906e-01,  7.26041287e-03]])

In [42]:
model.intercept_

array([-6.74051604])

In [30]:
model.predict(x_new)

array([1., 1.])

In [34]:
model = SVC(kernel='rbf')
results = cross_val_score(model, X, Y, cv=kfold)
print(results.mean())

0.760457963089542


In [35]:
model.fit(X,Y)

SVC()

In [37]:
model.predict(x_new)

array([0., 0.])

### Linear Discriminant Analysis

Henze-Zirkler Multivariate Normality Test in Python
https://www.statology.org/multivariate-normality-test-python/

In [27]:
#perform the Henze-Zirkler Multivariate Normality Test
pg.multivariate_normality(X, alpha=.05)

HZResults(hz=4.1804860273838855, pval=0.0, normal=False)

Вывод: отвергаем нулевую гипотезу о многомерной нормальности дискриминантных переменных.

In [37]:
pg.normality(dataframe)

W          pval  normal
preg   0.904278  1.608089e-21   False
plas   0.970104  1.986761e-11   False
pres   0.818921  1.584007e-28   False
skin   0.904627  1.751576e-21   False
test   0.722021  7.915248e-34   False
mass   0.949989  1.840562e-15   False
pedi   0.836519  2.477697e-27   False
age    0.874766  2.401947e-24   False
class  0.602510  1.292262e-38   False

Вывод: в соответствии с критерием Шапиро-Уилка ни один из признаков не имеет нормального распределения.

Box’s M test https://pingouin-stats.org/generated/pingouin.box_m.html

In [34]:
pg.box_m(dataframe, dvs=['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age'], group='class')

AttributeError: module 'pingouin' has no attribute 'box_m'

В colab отработал. Ковариационные матрицы для разных классов не равны.

In [35]:
#Проверка линейной независимости дискриминантных переменных
pg.pairwise_corr(dataframe, columns=['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age'], method='pearson')

X     Y   method       tail    n         r           CI95%  \
0   preg  plas  pearson  two-sided  768  0.129459     [0.06, 0.2]   
1   preg  pres  pearson  two-sided  768  0.141282    [0.07, 0.21]   
2   preg  skin  pearson  two-sided  768 -0.081672  [-0.15, -0.01]   
3   preg  test  pearson  two-sided  768 -0.073535   [-0.14, -0.0]   
4   preg  mass  pearson  two-sided  768  0.017683   [-0.05, 0.09]   
5   preg  pedi  pearson  two-sided  768 -0.033523    [-0.1, 0.04]   
6   preg   age  pearson  two-sided  768  0.544341    [0.49, 0.59]   
7   plas  pres  pearson  two-sided  768  0.152590    [0.08, 0.22]   
8   plas  skin  pearson  two-sided  768  0.057328   [-0.01, 0.13]   
9   plas  test  pearson  two-sided  768  0.331357    [0.27, 0.39]   
10  plas  mass  pearson  two-sided  768  0.221071    [0.15, 0.29]   
11  plas  pedi  pearson  two-sided  768  0.137337    [0.07, 0.21]   
12  plas   age  pearson  two-sided  768  0.263514     [0.2, 0.33]   
13  pres  skin  pearson  two-sided  768  0.207371    [0.14, 0.27]   
14  pres  test  pearson  two-sided  768  0.088933    [0.02, 0.16]   
15  pres  mass  pearson  two-sided  768  0.281805    [0.22, 0.35]   
16  pres  pedi  pearson  two-sided  768  0.041265   [-0.03, 0.11]   
17  pres   age  pearson  two-sided  768  0.239528    [0.17, 0.31]   
18  skin  test  pearson  two-sided  768  0.436783    [0.38, 0.49]   
19  skin  mass  pearson  two-sided  768  0.392573    [0.33, 0.45]   
20  skin  pedi  pearson  two-sided  768  0.183928    [0.11, 0.25]   
21  skin   age  pearson  two-sided  768 -0.113970  [-0.18, -0.04]   
22  test  mass  pearson  two-sided  768  0.197859    [0.13, 0.26]   
23  test  pedi  pearson  two-sided  768  0.185071    [0.12, 0.25]   
24  test   age  pearson  two-sided  768 -0.042163   [-0.11, 0.03]   
25  mass  pedi  pearson  two-sided  768  0.140647    [0.07, 0.21]   
26  mass   age  pearson  two-sided  768  0.036242   [-0.03, 0.11]   
27  pedi   age  pearson  two-sided  768  0.033561    [-0.04, 0.1]   

           p-unc       BF10     power  
0   3.219491e-04     28.791  0.949814  
1   8.541846e-05    100.059  0.975945  
2   2.360795e-02      0.583  0.619944  
3   4.162094e-02      0.359  0.531407  
4   6.246376e-01      0.051  0.077839  
5   3.535346e-01      0.069  0.152973  
6   1.862813e-60   9.03e+56  1.000000  
7   2.169507e-05    366.214  0.989169  
8   1.124141e-01      0.159  0.355230  
9   3.882624e-21  8.929e+17  1.000000  
10  5.891413e-10  9.293e+06  0.999990  
11  1.345878e-04     65.209  0.968913  
12  1.150112e-13  3.936e+10  1.000000  
13  6.606687e-09   8.86e+05  0.999944  
14  1.368350e-02      0.939  0.694191  
15  1.737888e-15  2.415e+12  1.000000  
16  2.533744e-01      0.087  0.207803  
17  1.752051e-11  2.869e+08  0.999999  
18  4.043577e-37  5.944e+33  1.000000  
19  1.054876e-29  2.645e+26  1.000000  
20  2.856179e-07  2.316e+04  0.999286  
21  1.558278e-03      6.673  0.886463  
22  3.219695e-08  1.908e+05  0.999834  
23  2.402264e-07  2.737e+04  0.999363  
24  2.431822e-01      0.089  0.214909  
25  9.197970e-05     93.315  0.974912  
26  3.158330e-01      0.075  0.170892  
27  3.529797e-01       0.07  0.153217

Вывод: сила линейной связи между дискриминантными переменными невысокая.

Проводить дискриминантный анализ нельзя, т.к. не выполнены предпосылки, а именно нет равенства ковариационных матриц для каждого класса и нет многомерной нормальности распределения дискриминантных переменных.

In [67]:
# LDA Classification
model = LinearDiscriminantAnalysis()
results = cross_val_score(model, X, Y, cv=kfold)
print(results.mean())
print(results.std())

0.7669685577580315
0.04796563054016723


In [68]:
model.fit(X,Y)

LinearDiscriminantAnalysis()

In [45]:
model.predict(x_new)

array([1., 1.])

In [46]:
model.predict_proba(x_new)

array([[0.13996295, 0.86003705],
       [0.10537183, 0.89462817]])

https://towardsdatascience.com/linear-discriminant-analysis-in-python-76b8b17817c2

https://machinelearningmastery.com/linear-discriminant-analysis-with-python/

In [69]:
model.transform(X)[:5]

array([[ 1.38024702],
       [-1.56452399],
       [ 1.76618515],
       [-1.69058752],
       [ 2.20726804]])

In [70]:
#Значения дискриминантной функции. Она одна (количество классов минус 1): 2-1
X_lda=model.fit_transform(X,Y)
X_lda[:5]

array([[ 1.38024702],
       [-1.56452399],
       [ 1.76618515],
       [-1.69058752],
       [ 2.20726804]])

In [71]:
#We can access the following property to obtain the variance explained by each component.
model.explained_variance_ratio_

array([1.])